namespace Pathhack.Dat;

public static class Hallucinations
{
    public static readonly string[] BogusMonsters = [
        "jumbo shrimp",
        "giant pigmy",
        "gnu",
        "killer penguin",
        "Hexley",
        "lemming with a suicide vest",
        "giant cockroach",
        "giant slug",
        "maggot",
        "pterodactyl",
        "tyrannosaurus rex",
        "basilisk",
        "efreeti",
        "dao",
        "rot grub",
        "bookworm",
        "Euryale",
        "Stheno",
        "The X",
        "demi lichen",
        "master lichen",
        "arch-lichen",
        "demiwitch",
        "priest of a well-known god",
        "shallow one",
        "fungi from your-sock",
        "mochtroid",
        "youtroid",
        "serge-ant",
        "lieuten-ant",
        "captant",
        "shadow",
        "hologram",
        "jester",
        "attorney",
        "sleazoid",
        "killer tomato",
        "shrinking violet",
        "amazon",
        "mermaid",
        "gynoid",
        "magical girl",
        "wild man",
        "merman",
        "android",
        "shonen hero",
        "delinquent",
        "robot",
        "battlemech",
        "rhinovirus",
        "harpy",
        "lion-dog",
        "rat-ant",
        "bot for announcing commits",
        "bot for evaluating code",
        "message-sending bot",
        "bot for hugging people",
        "channel-occupying bot",
        "verbally abusive bot (with great taste in endgame-content)",
        "discordian bot",
        "smartbot overlord",
        "Y2K bug",
        "foo",
        "neutral twin",
        "vampiric half-dragon half-troll lycanthropic fiendish snail",
        "squid thingy",
        "allegedly-matriarchal drow",
        "ranch dressing semielemental",
        "Christmas-tree monster",
        "luck sucker",
        "paskald",
        "brogmoid",
        "dornbeast",
        "Ancient Multi-Hued Dragon",
        "Evil Iggy",
        "rattlesnake",
        "ice monster",
        "phantom",
        "quagga",
        "aquator",
        "griffin",
        "emu",
        "kestrel",
        "xeroc",
        "venus flytrap",
        "creeping coins",
        "hydra",
        "siren",
        "jotun",
        "killer bunny",
        "P. o. t. U. S.",
        "R. o. U. S.",
        "bear named Smokey",
        "5.9176 pentranomeker worm",
        "int64_t worm",
        "andalite",
        "yithian",
        "elder thing",
        "old one",
        "great old one",
        "outer god",
        "other god",
        "elder god",
        "eyeless albino penguin",
        "shadowgirl",
        "Luggage",
        "God of Stuff",
        "vampiric watermelon",
        "fearsome madeofplasticoid",
        "Ent",
        "tangle tree",
        "nickelpede",
        "wiggle",
        "white rabbit",
        "snark",
        "pushmi-pullyu",
        "smurf",
        "tribble",
        "Klingon",
        "Borg",
        "Ewok",
        "Wookiee",
        "Jedi",
        "Sith",
        "incredible hulk",
        "incredible bulk",
        "hegemonic brute",
        "sovereign slayer",
        "draconian dignitary",
        "courtyard droll",
        "sprit named Totoro",
        "ohmu",
        "youma",
        "Lone Power",
        "electric boid",
        "feral waffle-iron",
        "Bowman's wolf",
        "worried machine",
        "omniquantalist",
        "squid in a space-suit",
        "carbosilicate amorph",
        "debatably-sapient kreely",
        "viral boy-band",
        "self-replicating, self-aware war machine",
        "maximally effective mercenary",
        "friend demon",
        "unicorn jelly",
        "crystal basilisk",
        "big dumb object",
        "kaiju named Godzilla",
        "giant ape named King Kong",
        "earthquake beast",
        "shinigami captain",
        "shinigami lieutenant",
        "arrancar",
        "hollow",
        "nyaasu",
        "missingno.",
        "pikachu",
        "Invid",
        "Veritech",
        "berserk Eva",
        "boomer",
        "Dalek",
        "microscopic space fleet",
        "Ravenous Bugblatter Beast of Traal",
        "dolphin",
        "teenage mutant ninja turtle",
        "samurai rabbit",
        "aardvark",
        "Audrey II",
        "witch doctor",
        "one-eyed one-horned flying purple people eater",
        "purple dinosaur",
        "sparkly vampire",
        "Morgoth",
        "Terminator",
        "Cylon",
        "Vorlon",
        "Mondoshawan",
        "Tralfamadorian",
        "RIME",
        "Ch'Thone",
        "palaeotech",
        "wheeler",
        "spindle king",
        "kung",
        "shand",
        "questing beast",
        "Predator",
        "mother-in-law",
        "visible stalker",
        "Minosaur",
        "vestigal virgin",
        "octagenarian",
        "spherical cow",
        "arsassin",
        "booksh elves",
        "amazing tommy-gun nun",
        "one-winged dewinged stab-bat",
        "praying mantis",
        "arch-pedant",
        "beluga whale",
        "bluebird of happiness",
        "bouncing eye",
        "floating nose",
        "buffer overflow",
        "dangling pointer",
        "walking disk drive",
        "cacodemon",
        "scrag",
        "cardboard golem",
        "duct tape golem",
        "chess pawn",
        "chicken",
        "chocolate pudding",
        "coelacanth",
        "corpulent porpoise",
        "Crow T. Robot",
        "diagonally moving grid bug",
        "dropbear",
        "@ named Dudley",
        "El Pollo Diablo",
        "evil overlord",
        "existential angst",
        "figment of your imagination",
        "flash of insight",
        "flying pig",
        "gazebo",
        "gonzo journalist",
        "gray goo",
        "magnetic monopole",
        "ooblecks",
        "heisenbug",
        "lag monster",
        "loan shark",
        "Lord British",
        "newsgroup troll",
        "ninja pirate zombie robot",
        "octarine dragon",
        "particle man",
        "possessed waffle iron",
        "poultrygeist",
        "raging nerd",
        "roomba",
        "sea cucumber",
        "spelling bee",
        "Strong Bad",
        "stuffed raccoon puppet",
        "tapeworm",
        "liger",
        "velociraptor",
        "vermicious knid",
        "viking",
        "voluptuous ampersand",
        "wee green blobbie",
        "wereplatypus",
        "zergling",
        "hag of bolding",
        "blancmange",
        "killer beet",
        "land octopus",
        "frog prince",
        "slow loris",
        "dust speck",
        "kitten prospecting robot",
        "angry mariachi",
        "manbearpig",
        "star-nosed mole",
        "acid blog",
        "guillemet",
        "solidus",
        "obelus",
        "miniature blimp",
        "lungfish",
        "grain neutral spirit",
        "hard-to-destroy reptile",
        "shy guy",
        "apostrophe golem",
        "angry flower named Bob",
        "bonsai-kitten",
        "Boxxy",
        "lonelygirl15",
        "tie-thulu",
        "Domo-kun",
        "looooooooooooong cat",
        "bohrbug",
        "mandelbug",
        "schroedinbug",
        "clockwork bug",
        "rabbit named Gerbenok",
        "doenertier",
        "Invisible Pink Unicorn",
        "Flying Spaghetti Monster",
        "Bluebear",
        "Professor Abdullah Nightingale",
        "Qwerty Uiop",
        "troglotroll",
        "wolpertinger",
        "elwedritsche",
        "skvader",
        "Nessie",
        "tatzelwurm",
        "dahu",
        "bigfoot",
        "tree octopus",
        "mothman",
        "three-headed monkey",
        "little green man",
        "weighted Companion Cube",
        "Oracle turret",
        "morality core",
        "/b/tard",
        "manbearpig",
        "ceiling cat",
        "basement cat",
        "monorail cat",
        "tridude",
        "orcus cosmicus",
        "yeek",
        "quylthulg",
        "Greater Hell Beast",
        "Vendor of Yizard",
        "Sigmund",
        "lernaean hydra",
        "Ijyb",
        "Gloorx Vloq",
        "Blork the orc",
        "unicorn pegasus kitten",
        "nyan cat",
        "grind bug",
        "enderman",
        "wight supremacist",
        "wizard named Magical Trevor",
        "first category perpetual motion device",
        "ghoti",
        "regex engine",
        "netsplit",
        "wiki",
        "peer",
        "pigasus",
        "Semigorgon",
        "meeple",
        "conventioneer",
        "terracotta warrior",
        "large microbat",
        "small megabat",
        "uberhulk",
        "hearse",
        "COBOL",
        "tofurkey",
        "hippocampus",
        "hippogriff",
        "kelpie",
        "gloating eye",
        "flush golem",
        "martyr orc",
        "mortar orc",
        "acute blob",
        "aria elemental",
        "aliasing priest",
        "aligned parasite",
        "aligned parquet",
        "aligned proctor",
        "baby balky dragon",
        "baby blues dragon",
        "baby caricature",
        "baby crochet",
        "baby grainy dragon",
        "baby bong worm",
        "baby long word",
        "baby parable worm",
        "barfed devil",
        "beer wight",
        "boor wight",
        "brawny mold",
        "rave spider",
        "clue golem",
        "bust vortex",
        "errata elemental",
        "elastic eel",
        "electrocardiogram eel",
        "fir elemental",
        "tire elemental",
        "flamingo sphere",
        "fallacy golem",
        "frizzed centaur",
        "forest centerfold",
        "fierceness sphere",
        "frosted giant",
        "geriatric snake",
        "gnat ant",
        "giant bath",
        "grant beetle",
        "giant mango",
        "glossy golem",
        "gnome laureate",
        "gnome dummy",
        "gooier ooze",
        "green slide",
        "guardian nacho",
        "hell hound pun",
        "high purist",
        "hairnet devil",
        "ice trowel",
        "feather golem",
        "lounge worm",
        "mountain lymph",
        "pager golem",
        "pie fiend",
        "prophylactic worm",
        "sock mole",
        "rogue piercer",
        "seesawing sphere",
        "simile mimic",
        "moldier ant",
        "stain vortex",
        "scone giant",
        "umbrella hulk",
        "vampire mace",
        "verbal jabberwock",
        "water lemon",
        "water melon",
        "winged grizzly",
        "yellow wight",
        "weeping angle",
        "gelatinous sphere",
        "gelatinous pyramid",
        "gelatinous Klein bottle",
        "gelatinous Mandelbrot set",
        "array terminator",
    ];

    public static readonly string[] BogusItems = [
        "eleven arrow",
        "ortish arrow",
        "ruined arrow",
        "vulgar arrow",
        "ja",
        "bamboozled sparrow",
        "crossbow colt",
        "crossbow dolt",
        "throwing fart",
        "shurunken",
        "bomberang",
        "elven drear",
        "orcish dear",
        "dwarvish peer",
        "sliver spear",
        "throwing spar",
        "2x3dent",
        "danger",
        "elven danger",
        "orcish danger",
        "sliver danger",
        "allthame",
        "scalp",
        "stiletto",
        "silletto",
        "criesknife",
        "old battle-axe",
        "length-challenged sword",
        "re-curved sword",
        "de-curved sword",
        "circular sword",
        "longer sword",
        "three-handed sword",
        "two-handled sword",
        "catana",
        "dunesword",
        "bi-partisan",
        "parisian",
        "sniptem",
        "fave",
        "rancor",
        "lancer",
        "halbeard",
        "snake-eyed bardiche",
        "vouge",
        "dwarvish hassock",
        "fauchard",
        "mysarme",
        "uisarme",
        "bob-guisarme",
        "lucifer's hammer",
        "bec de corwin",
        "yet another poorly-differentiated polearm",
        "cursed YAPDP",
        "basket-case broadsword",
        "can of mace",
        "evening star",
        "dawn star",
        "day star",
        "peace hammer",
        "wooden sandwich",
        "halfstaff",
        "thong club",
        "dire flail",
        "dire fail",
        "trollwhip",
        "partially-eaten yumi",
        "X-bow",
        "conical flat",
        "mithril-boat",
        "barded mail",
        "yet-another-substandard-mail-variant",
        "cursed YASMV",
        "scale-reinforced banded splint mail with chain joints",
        "leather studd armor",
        "white shirt",
        "red shirt",
        "pair of brown pants",
        "undershirt",
        "cope [sic]",
        "cope [with it]",
        "lion skin",
        "lion sin",
        "bear skin robe",
        "bear skin rug",
        "undersized shield",
        "shield of reflection",
        "shield of rarefaction",
        "wide-eyed shield",
        "pair of padding gloves",
        "pair of rideable gloves",
        "pair of feching gloves",
        "pair of wandering walking shoes",
        "pair of walkabout shoes",
        "pair of hardly shoes",
        "pair of jackboots",
        "pair of combat boats",
        "pair of hiking boots",
        "pair of wild hiking boots",
        "pair of muddy boots",
        "gnomerang",
        "gnagger",
        "hipospray ampule",
        "can of Greece",
        "can of crease",
        "can of Grease",
        "can of greaser",
        "cursed boomerang axe",
        "blessed greased +5 silly object of hilarity",
        "kinda lame joke",
        "brazier of commanding fire elementals",
        "brassiere of commanding fire elementals",
        "bowl of commanding water elementals",
        "bowel of commanding water elementals",
        "censer of controlling air elementals",
        "censure of controlling air elementals",
        "stone of controlling earth elementals",
        "loan of controlling earth elementals",
        "polo mallet",
        "string vest",
        "applied theology textbook",
        "handbag",
        "onion ring",
        "tuxedo",
        "breath mint",
        "potion of antacid",
        "potion of wokitoff",
        "potion of hull feeling",
        "traffic cone",
        "chainsaw",
        "pair of high-heeled stilettos",
        "high-heeled stiletto",
        "comic book",
        "lipstick",
        "dinner-jacket",
        "three-piece suit",
        "left-handed iron chain",
        "holy hand grenade",
        "decoder ring",
        "amulet of huge gold chains",
        "rubber Marduk",
        "unicron horn",
        "holy grail",
        "chainmail bikini",
        "leather shorts",
        "first class one-way ticket to Albuquerque",
        "yellow spandex dragon scale mail",
        "grand piano",
        "set of two slightly sampled electric eels",
        "kick drum",
        "tooled airhorn",
        "flux capacitor",
        "Walther PPK",
        "hanging chad",
        "99 red balloons",
        "pincers of peril",
        "ring of schwartz",
        "signed copy of Diaspora",
        "file containing the missing evidence in the Kelner case",
        "blessed 9 helm of Des Lynam",
        "oscillation overthruster",
        "magic device",
        "Infinity Gauntlet",
        "AAA chipset",
        "thoroughly used copy of Nethack for Dummies",
        "named pipe",
        "kernel trap",
        "copy of nethack 3.4.4",
        "YAFM",
        "YAAP",
        "YANI",
        "YAAD",
        "YASD",
        "YAFAP",
        "malevolent RNG",
        "cursed smooth manifold",
        "vi clone",
        "maximally subsentient emacs mode",
        "bongard diagram",
        "pair of Joo Janta 200 Super-Chromatic Peril Sensitive Sunglasses",
        "smooth-gemmed head-ch102020202020202020202020202020202020202020202",
        "overloading phaser",
        "thermal detinator",
        "thing that is not tea",
        "potion almost, but not quite, entirely unlike tea",
        "potion of Pan-Galactic Gargle Blaster",
        "black scroll-case labeled DON'T PANIC",
        "ridiculously dangerous epaulet [it's armed]",
        "pokeball",
        "scroll of oxygen-destroyer plans",
        "hologram of Death Star plans",
        "sonic screwdriver",
        "bum bag",
        "blessed tin of marmite",
        "tesco value potion",
        "ringtone of drawbridge opening",
        "burberry cap",
        "potion of bitter",
        "cursed -2 bargain plane ticket to Ibiza",
        "black pudding corpse",
        "leaf of pipe weed",
        "knife missile",
        "large gem",
        "ring of power",
        "silmaril",
        "pentagram of protection",
        "crown of swords",
        "memetic kill agent",
        "global retrocausality torus",
        "bottle of squid pro quo ink",
        "highly indulgent self-insert",
        "cursed -1 phillips head",
        "sampo",
        "shamir",
        "golden fleece",
        "gold apple",
        "Holy Grail",
        "Ark of the Covenant",
        "Chaos Emerald",
        "bronze sphere",
        "modron cube",
        "monster manual",
        "monster book of monsters",
        "Codex of the Infinite Planes",
        "spellbook of Non-Conduit Transdimensional Fabric Fluxes and Real-Time Inter-dimensional Matrix Transformations",
        "spellbook named the Codex of Betrayal",
        "spellbook named the Demonomicon of Iggwilv",
        "spellbook named the Book of Keeping",
        "Black Scroll of Ahm",
        "Elder Scroll",
        "spellbook named The Ta'ge Fragments",
        "spellbook named Tome of Eternal Darkness",
        "history book called A Chronicle of the Daevas",
        "spellbook named The Book of Sand",
        "spellbook named Octavo",
        "spellbook called Necrotelicomnicon",
        "lost copy of The Nice and Accurate Prophecies of Anges Nutter",
        "spellbook of Addition Made Simple",
        "spellbook of Noncommutative Hyperdimensional Geometry Made (Merely!) Complicated",
        "heavily obfuscated spellbook",
        "scroll of abstruse logic",
        "scroll of identity",
        "scroll of cure blindness",
        "spellbook of sub-formal introtransreductive logic [for Dummies!]",
        "spellbook named A Brief History of Time",
        "spellbook named The Book of Eibon",
        "playbook named The King in Yellow",
        "playbook called the Scottish play",
        "spellbook named De Vermis Mysteriis",
        "HANDBOOK FOR THE IMMINENTLY DECEASED named ~ATH",
        "spellbook named Necronomicon",
        "spellbook named Al Azif",
        "spellbook named Unaussprechlichen Kulten",
        "spellbook called Nameless Cults",
        "spellbook called Unspeakable Cults",
        "spellbook called Unpronouncable Cults",
        "spellbook named The Diary of Drenicus the Wise",
        "spellbook named Clavicula Salomonis Regis",
        "copy of The Five Books of Moses",
        "spellbook named The Six and Seventh Books of Moses",
        "spellbook named The Book of Coming Forth by Day",
        "spellbook named The Book of emerging forth into the Light",
        "spellbook named Sepher Ha-Razim",
        "spellbook named Sefer Raziel HaMalakh",
        "spellbook named The Testament of Solomon",
        "spellbook named The Book of Enoch",
        "spellbook named The Book of Inverted Darkness",
        "spellbook named The Uruk Tablets",
        "spellbook named The Book of the Law",
        "spellbook named the Book of Shadows",
        "spellbook named the Book of Mirrors",
        "book called the Gospel of the Thricefold Exile",
        "dead sea scroll",
        "mayan codex",
        "simple textbook on the zoologically dubious",
        "spellbook named The Book of Night with Moon",
        "spellbook named The Grimmerie",
        "book of horrors",
        "book of Remembrance and Forgetting",
        "Amarna letter",
        "lost ark of the covenant",
        "cat o'nine tails",
        "piece of eight",
        "codpiece",
        "straight-jacket",
        "bayonet",
        "iron maiden",
        "oubliette",
        "pestle and mortar",
        "plowshare",
        "petard",
        "caltrop",
        "potion of rebigulation",
        "potion of score doubling",
        "potion of bad breath",
        "potion of fire breathing",
        "potion of intoxication",
        "potion of immorality",
        "potion of immoratlity",
        "potion of gain divinity",
        "scroll labeled ED AWK YACC",
        "scroll labeled RTFM",
        "scroll labeled KLAATU BARADA NIKTO",
        "scroll of omniscience",
        "scroll of mash keyboard",
        "scroll of RNG taming",
        "scroll of fungicide",
        "scroll of apocalypse",
        "scroll of profits",
        "scroll of stupidity",
        "spellbook of firebear",
        "spellbook of dip",
        "spellbook of cone of cord",
        "helm of telemetry",
        "helm of head-butting",
        "pair of blue suede boots of charisma",
        "pair of boots of rug-cutting",
        "pair of cursed boots of mazing",
        "pair of wisdom boots",
        "cubic zirconium",
        "amulet of instadeath",
        "amulet of bad luck",
        "amulet of refraction",
        "amulet of deflection",
        "amulet of rarefaction",
        "amulet versus YASD",
        "O-ring",
        "ring named Frost Band",
        "expensive exact replica of the Amulet of Yendor",
        "giant beatle",
        "lodestone",
        "rubber chicken",
        "figurine of a god",
        "tin of Player meat",
        "tin of whoop ass",
        "ragnarok horn",
        "cursed -3 earring of adornment",
        "ornamental cape",
        "acid blob skeleton",
        "wand of washing",
        "wand of intoxication",
        "wand of vaporization",
        "wand of disruption",
        "wand of transubstantiation",
        "wand of disintegration",
        "wand of renewal",
        "little piece of home",
        "brand new, all time lowest introductory rate special offer",
        "tin of spam",
        "dirty rag",
    ];
}
