using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Bee;

[Generator]
public class ConfigGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var configClass = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: (node, _) => node is RecordDeclarationSyntax r && r.Identifier.Text == "ConfigData",
            transform: (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol)
            .Where(s => s != null);

        context.RegisterSourceOutput(configClass.Collect(), Generate!);
    }

    static void Generate(SourceProductionContext ctx, ImmutableArray<INamedTypeSymbol> types)
    {
        var type = types.FirstOrDefault();
        if (type == null) return;

        var props = type.GetMembers().OfType<IPropertySymbol>()
            .Where(p => p.SetMethod != null && p.DeclaredAccessibility == Accessibility.Public)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("namespace Pathhack.Game;");
        sb.AppendLine();
        sb.AppendLine("public static partial class Config");
        sb.AppendLine("{");

        GenerateNormalize(sb);
        sb.AppendLine();
        GenerateIsBoolOption(sb, props);
        sb.AppendLine();
        GenerateTrySetBool(sb, props);
        sb.AppendLine();
        GenerateTrySetCompound(sb, props);

        sb.AppendLine("}");

        ctx.AddSource("Config.g.cs", sb.ToString());
    }

    static string Normalize(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var c in name)
            if (c != '_') sb.Append(char.ToLowerInvariant(c));
        return sb.ToString();
    }

    static void GenerateNormalize(StringBuilder sb)
    {
        sb.AppendLine("    static string Normalize(string name) => name.Replace(\"_\", \"\").ToLowerInvariant();");
    }

    static void GenerateIsBoolOption(StringBuilder sb, List<IPropertySymbol> props)
    {
        sb.AppendLine("    static bool IsBoolOption(string key)");
        sb.AppendLine("    {");
        sb.AppendLine("        var k = Normalize(key);");
        sb.AppendLine("        return k switch");
        sb.AppendLine("        {");
        foreach (var p in props)
        {
            if (p.Type.SpecialType != SpecialType.System_Boolean) continue;
            sb.AppendLine($"            \"{Normalize(p.Name)}\" => true,");
        }
        sb.AppendLine("            _ => false,");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    static void GenerateTrySetBool(StringBuilder sb, List<IPropertySymbol> props)
    {
        sb.AppendLine("    static bool TrySetBool(ConfigData data, string key, bool enable)");
        sb.AppendLine("    {");
        sb.AppendLine("        var k = Normalize(key);");
        sb.AppendLine("        return k switch");
        sb.AppendLine("        {");
        foreach (var p in props)
        {
            if (p.Type.SpecialType != SpecialType.System_Boolean) continue;
            var norm = Normalize(p.Name);
            sb.AppendLine($"            \"{norm}\" => Assign(ref data, d => d.{p.Name} = enable),");
        }
        sb.AppendLine("            _ => false,");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    static bool Assign(ref ConfigData data, System.Action<ConfigData> action) { action(data); return true; }");
    }

    static void GenerateTrySetCompound(StringBuilder sb, List<IPropertySymbol> props)
    {
        sb.AppendLine("    static bool TrySetCompound(ConfigData data, string key, string val)");
        sb.AppendLine("    {");
        sb.AppendLine("        var k = Normalize(key);");
        sb.AppendLine("        if (TrySetCompoundSpecial(data, k, val)) return true;");
        sb.AppendLine("        switch (k)");
        sb.AppendLine("        {");

        foreach (var p in props)
        {
            var norm = Normalize(p.Name);
            var t = p.Type;

            if (t.SpecialType == SpecialType.System_Boolean)
            {
                sb.AppendLine($"            case \"{norm}\":");
                sb.AppendLine($"                data.{p.Name} = val is \"true\" or \"1\" or \"on\" or \"yes\";");
                sb.AppendLine($"                return true;");
            }
            else if (t.SpecialType == SpecialType.System_Char)
            {
                sb.AppendLine($"            case \"{norm}\":");
                sb.AppendLine($"                if (val.Length == 1) data.{p.Name} = val[0];");
                sb.AppendLine($"                else if (int.TryParse(val, out int {norm}_ascii)) data.{p.Name} = (char){norm}_ascii;");
                sb.AppendLine($"                return true;");
            }
            else if (t.SpecialType == SpecialType.System_String)
            {
                sb.AppendLine($"            case \"{norm}\":");
                sb.AppendLine($"                data.{p.Name} = val;");
                sb.AppendLine($"                return true;");
            }
            else if (t.SpecialType == SpecialType.System_Int32)
            {
                sb.AppendLine($"            case \"{norm}\":");
                sb.AppendLine($"                if (int.TryParse(val, out int {norm}_i)) data.{p.Name} = {norm}_i;");
                sb.AppendLine($"                return true;");
            }
            else if (t.TypeKind == TypeKind.Enum)
            {
                GenerateEnumCase(sb, p, t);
            }
            // Skip collection types (PickupTypes, lists) — handled by special cases
        }

        sb.AppendLine("        }");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
    }

    static void GenerateEnumCase(StringBuilder sb, IPropertySymbol prop, ITypeSymbol enumType)
    {
        var norm = Normalize(prop.Name);
        var fullType = $"global::{GetFullName(enumType)}";
        var members = enumType.GetMembers().OfType<IFieldSymbol>()
            .Where(f => f.IsConst || (f.IsStatic && f.HasConstantValue))
            .ToList();

        sb.AppendLine($"            case \"{norm}\":");
        sb.AppendLine($"            {{");
        sb.AppendLine($"                var lval = val.ToLowerInvariant();");

        // Shorthand matching first
        bool hasAnyShorthand = false;
        foreach (var member in members)
        {
            var shorthands = GetShorthandChars(member);
            if (shorthands.Count == 0) continue;
            hasAnyShorthand = true;
        }

        if (hasAnyShorthand)
        {
            sb.AppendLine($"                if (lval.Length == 1)");
            sb.AppendLine($"                {{");
            sb.AppendLine($"                    switch (lval[0])");
            sb.AppendLine($"                    {{");
            foreach (var member in members)
            {
                var shorthands = GetShorthandChars(member);
                foreach (var ch in shorthands)
                    sb.AppendLine($"                        case '{ch}':");
                if (shorthands.Count > 0)
                {
                    sb.AppendLine($"                            data.{prop.Name} = {fullType}.{member.Name};");
                    sb.AppendLine($"                            return true;");
                }
            }
            sb.AppendLine($"                    }}");
            sb.AppendLine($"                }}");
        }

        // Full name matching
        foreach (var member in members)
        {
            sb.AppendLine($"                if (lval == \"{member.Name.ToLowerInvariant()}\") {{ data.{prop.Name} = {fullType}.{member.Name}; return true; }}");
        }

        // Numeric fallback for int-backed enums (NumberPad)
        sb.AppendLine($"                if (int.TryParse(val, out int {norm}_ev) && System.Enum.IsDefined(typeof({fullType}), {norm}_ev))");
        sb.AppendLine($"                    data.{prop.Name} = ({fullType}){norm}_ev;");

        sb.AppendLine($"                return true;"); // known key, bad value — don't warn
        sb.AppendLine($"            }}");
    }

    static List<char> GetShorthandChars(IFieldSymbol member)
    {
        var result = new List<char>();
        var attr = member.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "ShorthandAttribute");
        if (attr == null) return result;

        // Constructor args: params char[]
        foreach (var arg in attr.ConstructorArguments)
        {
            if (arg.Kind == TypedConstantKind.Array)
            {
                foreach (var elem in arg.Values)
                {
                    if (elem.Value is char c)
                        result.Add(c);
                }
            }
            else if (arg.Value is char c)
            {
                result.Add(c);
            }
        }
        return result;
    }

    static string GetFullName(ITypeSymbol type)
    {
        if (type.ContainingType != null)
            return $"{GetFullName(type.ContainingType)}.{type.Name}";
        var ns = type.ContainingNamespace;
        if (ns == null || ns.IsGlobalNamespace)
            return type.Name;
        return $"{ns.ToDisplayString()}.{type.Name}";
    }
}
